# Generated by Django 5.2.17 on 2026-08-14 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_id', models.CharField(max_length=255)),
                ('scenario_name', models.CharField(blank=True, max_length=255, null=True)),
                ('input_payload', models.JSONField()),
                ('audit_report', models.JSONField()),
                ('summary_status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('REQUIRES_REVIEW', 'Requires review')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
